# Generated by Django 5.1.6 on 2025-02-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='stu_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='stu_contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='stu_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='enrollment',
            new_name='stu_enrollment',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='stu_name',
        ),
    ]
